//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagdieva_Matie.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Service
    {
        public int ID { get; set; }
        public Nullable<int> ID_Master { get; set; }
        public Nullable<int> ID_Service { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
