//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagdieva_Matie.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterQualification
    {
        public int IDMaster { get; set; }
        public int ID_TypeQual { get; set; }
        public int ID { get; set; }
    
        public virtual TypeQualification TypeQualification { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
