//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagdieva_Matie.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IDOrder { get; set; }
        public Nullable<int> IDService { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> NumberInQueu { get; set; }
        public Nullable<int> IDWorker { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
